### ISSUE TITLE
HLS Explorer fails to get M3U8 variants from some servers

### ISSUE THREAD

**Issue by lprot** [mx3L/serviceapp#22]
If you play Replay.lv (LTV)->Last videos LV->any stream inside PlayStream plugin:
```
opkg install http://feed.blue.lv/enigma2-plugin-extensions-playstream_0.7v.ipk
```
The plugin constructs 4097 service and makes a call which is intercepted by ServiceApp.

You can see in the log stream_url  which is constructed by PlayStream:
```
stream_url= https://58174450afee9.streamlock.net/vod/smil:_definst_/e/f/ab433444.smil/playlist.m3u8?safwerwfasendtime=1521285783&safwerwfasstarttime=1521270927&safwerwfashash=THKMpCtQcNY7kq7IvqCL-4H84McMotqGvmY6S3ZpkLA= 
```
Then ServceApp makes SSL connect by using getVariantsFromMasterUrl: 
```
[getVariantsFromMasterUrl] - (SSL) Connected with ECDHE-RSA-AES256-GCM-SHA384 encryption
[getVariantsFromMasterUrl] - Request:
GET /vod/smil:_definst_/e/f/ab433444.smil/playlist.m3u8?safwerwfasendtime=1521285783&safwerwfasstarttime=1521270927&safwerwfashash=THKMpCtQcNY7kq7IvqCL-4H84McMotqGvmY6S3ZpkLA= HTTP/1.1
Host: 58174450afee9.streamlock.net
User-Agent: Enigma2 HbbTV/1.1.1 (+PVR+RTSP+DL;OpenPLi;;;)
Accept: */*
Connection: close
 
 
[getVariantsFromMasterUrl] Response[0](size=-1): H
[getVariantsFromMasterUrl] - wrong http response code: 739008800
```
  
But by some unknown reason it gets wrong response code. 

And it doesn't stop/report but passes master link to exteplayer that was unplayable there until v39:
```
PlayerApp::processStart: exteplayer3 "https://58174450afee9.streamlock.net/vod/smil:_definst_/e/f/ab433444.smil/playlist.m3u8?safwerwfasendtime=1521285783&safwerwfasstarttime=1521270927&safwerwfashash=THKMpCtQcNY7kq7IvqCL-4H84McMotqGvmY6S3ZpkLA=" 
```
Exteplayer v39 plays the link. But the question is open - we need to fix variant selection in HLS Explorer...

**Comment by mx3L** [comment]
Hello, currently I don't have enigma2 box with me, so I cannot test the plugin. Link is not valid anymore, please post me url to video on webpage.

**Comment by lprot** [comment]
https://replay.lsm.lv/ru/statja/lr/101168/guna-millersone-kultura-edinstvennoe-chto-ostalos/

**Comment by mx3L** [comment]
Hmm cant play it:

> 
Video ar ieslēgtu reklāmu bloķēšanas programmatūru nav iespējams skatīties. Mēģiniet skatīties šo video ar citu pārlūku, vai atslēdziet reklāmu bloķēšanas programmatūru!

**Comment by lprot** [comment]
Turn off adblocker :)

**Comment by mx3L** [comment]
:D lol, thanks next time I will try translator first

**Comment by mx3L** [comment]
looks like server is taking time to respond, since 3 seconds was not enough.

 I tried 10 seconds and it worked. Try https://github.com/mx3L/serviceapp/tree/test_increase_timeout branch and see if it works for you too..

**Comment by lprot** [comment]
Works like magic. Thanks!
