### ISSUE TITLE
How to set EXT3_PLAYBACK_AUDIO_TRACK_ID

### ISSUE THREAD

**Issue by technic** [mx3L/serviceapp#74]
There is a EXT3_PLAYBACK_AUDIO_TRACK_ID option, but I don't see it exposed to the python interface.

**Comment by mickd5** [comment]
Maybe this can help. Options that can be set by url

https://forums.openpli.org/topic/41198-serviceapp-gstplayer-and-exteplayer3/?view=findpost&p=763753

**Comment by technic** [comment]
Thanks for your answer! I will check it

**Comment by technic** [comment]
OK it works, but I now I need to be able to get the id of the track from python.

Can we also set `m_pid` here?

https://github.com/mx3L/serviceapp/blob/22f9aed2f87eb5361aa5fdd94589b47f2fae8a31/src/serviceapp/serviceapp.cpp#L904-L905

**Comment by technic** [comment]
I can make a PR but I don't have the set up toolchain at the moment. So could someone do it, and send it to me for testing? It should be one line change.

**Comment by mickd5** [comment]
The audio ID is usually dynamic for example dash manifest or variant playlist so it may not be the same for each stream. Can you parse the manifest or playlist with a python function first and then add the returned value to the play url so serviceapp will set and send the correct value to the player.

url = 'https://streamurl/stream.mpd' + '#sapp_audio_id=%s' % (returned_audioID)

**Comment by technic** [comment]
Hi,
In my case it is the same. And it is not in the m3u8-like playlist.

**Comment by mickd5** [comment]
OK so can you just set a static value and append to the play url? 

playurl + #sapp_audio_id=staticValue

**Comment by technic** [comment]
No. Because first I need to read out that value in the python code somehow.

**Comment by mickd5** [comment]
Can you download a sample of the media and parse using ffmpeg or gstreamer?  Maybe using popen to pipe the results?

**Comment by technic** [comment]
Why shall I do this?! Common, service app and extplayer already have all the required information, I see it in the logs. This is just one line patch.

**Comment by mickd5** [comment]
I assumed that you were writing about your own python  plugin and wanted to read the value there.

**Comment by technic** [comment]
@mickd5, I think it is possible to find a workaround like you are suggesting. Thanks for your ideas. However, my request here is to slightly improve the serviceapp, so that everyone one can not only get the audio track languages, but also get audio ids.

**Comment by technic** [comment]
@mickd5 could you please check it, I need it for openatv 6.4 on cortexa15hf-neon-vfpv4 or cortexa9hf-neon architecture.

**Comment by mickd5** [comment]
Compiled against develop branch and patched with your fix.  See does it work as expected. 

[https://www.dropbox.com/s/194nd9dsf0pvbbo/enigma2-plugin-systemplugins-serviceapp_0.5%2Bgit161%2B02956ea-r0_cortexa15hf-neon-vfpv4.ipk?dl=0](url)

**Comment by technic** [comment]
Ok... This patch works and I can get the audio id from the python code.
BUT, unfortunately the audio_id option does not work in the exteplayer3 :(
I see in the logs that serviceapp passes `-t someId` argument to exteplayer3, but it doesn't switch the audio track.

**Comment by technic** [comment]
> I see in the logs that serviceapp passes -t someId argument to exteplayer3, but it doesn't switch the audio track.

Oh. Damn it! After a look into the exteplayer3 sources I figured out that the `-t` option is not the **id** but the **index** of the audio track! facepalm.
